### ISSUE TITLE
Cannot download artifacts

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubekey#239]
![image](https://user-images.githubusercontent.com/22350668/90620629-49fa9080-e245-11ea-8228-e71e1ef90313.png)

**Comment by shaowenchen** [comment]
fixed
https://github.com/kubesphere/kubesphere/pull/2898

**Comment by huanggze** [comment]
not fixed @shaowenchen 

![image](https://user-images.githubusercontent.com/22350668/90853433-afb55c80-e3ac-11ea-8454-06917775ed38.png)

**Comment by shaowenchen** [comment]
disabled by the browser?

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/90854837-97474100-e3b0-11ea-98d5-fe286c953511.png)

**Comment by huanggze** [comment]
verified
